Repository LerianStudio/midaz-sdk-typescript, pull requests merged in 2025-05, with the labels that each got.

#21 feat: set workflow steps on repo
  .github/workflows/cache-deps.yml
  .github/workflows/changelog.yml
  .github/workflows/check-branch.yml
  .github/workflows/ci.yml
  .github/workflows/combined-analysis.yml
  .github/workflows/dependency-scan.yml
  .github/workflows/release.yml
  .releaserc.yml
Labels: feature

#22 feat: refactor and access manager implementation
  .env.example
  docs/utilities/config.md
  examples/config-example.ts
  src/client-config-builder.ts
  src/client.ts
  src/util/auth/access-manager.ts
  src/util/cache/cache.ts
  src/util/concurrency/concurrency.ts
  src/util/concurrency/rate-limiter.ts
  src/util/concurrency/worker-pool.ts
  src/util/config/config-service.ts
  src/util/error/error-handler.ts
  src/util/network/http-client.ts
  src/util/observability/observability-otel.ts
  src/util/observability/observability.ts
  src/util/validation/validation.ts
  tests/client-access-manager.test.ts
  tests/client-config-builder.test.ts
  tests/client-config-builder.test.ts.bak
  tests/util/auth/access-manager.test.ts
  tests/util/config/config-service.test.ts
  tests/util/formatting.test.ts
  tests/util/http-client-access-manager.test.ts
  tests/util/observability/logger.test.ts
Labels: feature

#35 Feature/pino integration
  package-lock.json
  package.json
  src/client.ts
  src/entities/entity.ts
  src/util/error/error-handler.ts
  src/util/network/http-client.ts
  src/util/observability/logger-instance.ts
  src/util/observability/logger.ts
  src/util/observability/pino-adapter.ts
  tests/util/config/config-service.test.ts
  tests/util/error/error-handler.test.ts
  tests/util/observability/logger.test.ts
  tests/util/observability/pino-adapter.test.ts
Labels: feature

#36 refactor: switch auth grant type from password to client credentials …
  examples/access-manager-example.ts
Labels: bug

#29 Develop
  .env.example
  .github/workflows/cache-deps.yml
  .github/workflows/changelog.yml
  .github/workflows/check-branch.yml
  .github/workflows/ci.yml
  .github/workflows/combined-analysis.yml
  .github/workflows/dependency-scan.yml
  .github/workflows/release.yml
  .releaserc.yml
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/utilities/config.md
  docs/utilities/network.md
  examples/access-manager-example.ts
  examples/config-example.ts
  package-lock.json
  package.json
  src/client-config-builder.ts
  src/client.ts
  src/entities/entity.ts
  src/util/auth/access-manager.ts
  src/util/cache/cache.ts
  src/util/concurrency/concurrency.ts
  src/util/concurrency/rate-limiter.ts
  src/util/concurrency/worker-pool.ts
  src/util/config/config-service.ts
  src/util/error/error-handler.ts
  src/util/network/http-client.ts
  src/util/observability/logger-instance.ts
  src/util/observability/logger.ts
  src/util/observability/observability-otel.ts
  src/util/observability/observability.ts
  src/util/observability/pino-adapter.ts
  src/util/validation/validation.ts
  tests/client-access-manager.test.ts
  tests/client-config-builder.test.ts
  tests/client-config-builder.test.ts.bak
  tests/util/auth/access-manager.test.ts
  tests/util/config/config-service.test.ts
  tests/util/error/error-handler.test.ts
  tests/util/formatting.test.ts
  tests/util/http-client-access-manager.test.ts
  tests/util/observability/logger.test.ts
  tests/util/observability/pino-adapter.test.ts
  tsconfig.json
Labels: released on @develop

#37 fix: set configuration on gptchangelog
  .github/workflows/release.yml
  src/util/config/config-service.ts
  tests/util/config/config-service.test.ts
Labels: bug

#45 fix(ci): restore disabled CI features and resolve pipeline failures
  .github/workflows/ci.yml
  .github/workflows/combined-analysis.yml
  package-lock.json
  package.json
  src/entities/implementations/accounts-impl.ts
  src/entities/implementations/assets-impl.ts
  src/entities/implementations/balances-impl.ts
  src/entities/implementations/ledgers-impl.ts
  src/entities/implementations/organizations-impl.ts
  src/entities/implementations/segments-impl.ts
  src/entities/implementations/transactions-impl.ts
  src/util/account/account-helpers.ts
  src/util/concurrency/rate-limiter.ts
  src/util/config/config-service.ts
  src/util/error/error-utils.ts
Labels: bug
